repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --config-file=pyproject.toml
        language: system
        types: [python]
        files: ^(aggregator|api|collector)/
        pass_filenames: false
        always_run: true