from aggregator.schemas import MetricPoint


class TimescaleDB:
    def __init__(self) -> None: ...

    async def connect(self) -> None: ...

    async def insert_metric(self, point: MetricPoint) -> None: ...

    async def close(self) -> None: ...
